#!/usr/bin/env python3
"""
Environment Setup Script
Reads credentials from details.md and configures .env files for backend and frontend
"""

import os
import re
from pathlib import Path

def read_credentials(details_file):
    """Read DATABASE_URL and BETTER_AUTH_SECRET from details.md"""
    if not os.path.exists(details_file):
        print(f"[ERROR] {details_file} not found")
        return None, None

    with open(details_file, 'r') as f:
        content = f.read()

    # Extract DATABASE_URL
    db_match = re.search(r'DATABASE_URL=(.+)', content)
    database_url = db_match.group(1).strip() if db_match else None

    # Extract BETTER_AUTH_SECRET
    secret_match = re.search(r'BETTER_AUTH_SECRET=(.+)', content)
    auth_secret = secret_match.group(1).strip() if secret_match else None

    return database_url, auth_secret

def validate_credentials(database_url, auth_secret):
    """Validate that credentials are properly formatted"""
    errors = []

    if not database_url:
        errors.append("DATABASE_URL is missing")
    elif database_url.startswith('[') or 'your-' in database_url.lower():
        errors.append("DATABASE_URL contains placeholder values - replace with actual credentials")
    elif not database_url.startswith('postgresql://'):
        errors.append("DATABASE_URL must start with 'postgresql://'")

    if not auth_secret:
        errors.append("BETTER_AUTH_SECRET is missing")
    elif len(auth_secret) < 32:
        errors.append(f"BETTER_AUTH_SECRET must be at least 32 characters (current: {len(auth_secret)})")
    elif 'your-secret' in auth_secret.lower() or 'change-this' in auth_secret.lower():
        errors.append("BETTER_AUTH_SECRET contains placeholder text - replace with actual secret")

    return errors

def create_backend_env(database_url, auth_secret, backend_dir):
    """Create backend/.env file"""
    env_content = f"""# Backend Environment Variables
# Generated by setup-env.py

# Database
DATABASE_URL={database_url}

# Authentication
BETTER_AUTH_SECRET={auth_secret}

# CORS
CORS_ORIGINS=http://localhost:3000

# Server
HOST=0.0.0.0
PORT=8000
ENVIRONMENT=development
"""

    env_file = os.path.join(backend_dir, '.env')
    with open(env_file, 'w') as f:
        f.write(env_content)

    print(f"[OK] Created: {env_file}")

def create_frontend_env(auth_secret, frontend_dir):
    """Create frontend/.env.local file"""
    env_content = f"""# Frontend Environment Variables
# Generated by setup-env.py

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:8000

# Authentication
BETTER_AUTH_SECRET={auth_secret}
BETTER_AUTH_URL=http://localhost:3000
"""

    env_file = os.path.join(frontend_dir, '.env.local')
    with open(env_file, 'w') as f:
        f.write(env_content)

    print(f"[OK] Created: {env_file}")

def main():
    print("Phase 2 Environment Setup")
    print("=" * 50)

    # Paths
    base_dir = Path(__file__).parent
    details_file = base_dir / 'details.md'
    backend_dir = base_dir / 'project' / 'backend'
    frontend_dir = base_dir / 'project' / 'frontend'

    # Read credentials
    print(f"\nReading credentials from: {details_file}")
    database_url, auth_secret = read_credentials(details_file)

    # Validate
    print("\nValidating credentials...")
    errors = validate_credentials(database_url, auth_secret)

    if errors:
        print("\n[ERROR] Validation failed:")
        for error in errors:
            print(f"   - {error}")
        print("\nPlease update details.md with valid credentials and run this script again.")
        return 1

    print("[OK] Credentials validated successfully")

    # Create .env files
    print("\nCreating environment files...")

    if not backend_dir.exists():
        print(f"[ERROR] Backend directory not found: {backend_dir}")
        return 1

    if not frontend_dir.exists():
        print(f"[ERROR] Frontend directory not found: {frontend_dir}")
        return 1

    create_backend_env(database_url, auth_secret, backend_dir)
    create_frontend_env(auth_secret, frontend_dir)

    print("\n" + "=" * 50)
    print("[SUCCESS] Environment setup complete!")
    print("\nNext steps:")
    print("   1. Install backend dependencies:")
    print("      cd project/backend")
    print("      python -m venv venv")
    print("      venv\\Scripts\\activate  (Windows)")
    print("      pip install -r requirements.txt")
    print("\n   2. Run backend tests:")
    print("      pytest")
    print("\n   3. Start backend server:")
    print("      uvicorn app.main:app --reload")
    print("\n   4. In another terminal, start frontend:")
    print("      cd project/frontend")
    print("      npm run dev")
    print("\n   5. Open browser: http://localhost:3000")
    print("=" * 50)

    return 0

if __name__ == '__main__':
    exit(main())
