apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  # Kafka broker connection
  - name: brokers
    value: "kafka-service:9092"
  - name: consumerGroup
    value: "todo-app-group"
  - name: clientId
    value: "todo-app"

  # Authentication (optional)
  # - name: authType
  #   value: "password"
  # - name: saslUsername
  #   secretKeyRef:
  #     name: kafka-secrets
  #     key: username
  # - name: saslPassword
  #   secretKeyRef:
  #     name: kafka-secrets
  #     key: password

  # Topic configuration
  - name: initialOffset
    value: "newest"
  - name: maxMessageBytes
    value: "1024000"

  # Consumer configuration
  - name: consumeRetryInterval
    value: "200ms"
  - name: version
    value: "2.8.0"
